# Generated by Django 2.2.7 on 2019-12-09 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('timeline', models.CharField(max_length=25)),
                ('requirements', models.CharField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('positions', models.CharField(max_length=75)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('skills', models.CharField(choices=[('1', 'HTML/CSS'), ('2', 'Wordpress'), ('3', 'JavaScript'), ('4', 'Ruby'), ('5', 'Django'), ('6', 'GOlang')], default='', max_length=30)),
                ('current_projects', models.CharField(default='', max_length=20)),
                ('old_projects', models.CharField(default='', max_length=20)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Accepted'), ('r', 'Rejected')], default='', max_length=2)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Profile')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Position')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Project')),
            ],
        ),
    ]
