# Generated by Django 2.2.9 on 2020-01-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='related_skill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teams.Skill'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
