# Generated by Django 2.2.7 on 2019-12-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20191210_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(choices=[('1', 'HTML/CSS'), ('2', 'Wordpress'), ('3', 'JavaScript'), ('4', 'Ruby'), ('5', 'Django'), ('6', 'GOlang')], default='', max_length=30),
        ),
    ]
