# Generated by Django 2.2.7 on 2019-12-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20191210_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(default='', max_length=100),
        ),
    ]
