# Generated by Django 2.2.7 on 2019-12-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20191210_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_name',
            field=models.ManyToManyField(to='teams.Skill'),
        ),
    ]
