# Generated by Django 2.2.7 on 2019-12-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20191210_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
