# Generated by Django 2.2.7 on 2019-12-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20191217_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ProfileSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Skill')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Profile')),
            ],
        ),
    ]
