# Generated by Django 2.2.7 on 2019-12-18 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20191218_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskills',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
