# Generated by Django 2.2.7 on 2019-12-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20191218_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileskills',
            name='skills',
        ),
        migrations.AddField(
            model_name='profileskills',
            name='skills',
            field=models.ManyToManyField(to='teams.Skill'),
        ),
    ]
