# Generated by Django 3.0.1 on 2019-12-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20191218_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskills',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Profile'),
        ),
    ]
