# Generated by Django 3.0.1 on 2019-12-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20191219_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileSkills',
        ),
    ]
