# Generated by Django 3.0.1 on 2019-12-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_delete_profileskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='username',
            field=models.ManyToManyField(to='teams.Profile'),
        ),
    ]
