# Generated by Django 3.0.1 on 2019-12-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_skill_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
