# Generated by Django 3.0.1 on 2019-12-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20191221_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='teams.Skill'),
        ),
        migrations.DeleteModel(
            name='SkillProfile',
        ),
    ]
