# Generated by Django 3.0.1 on 2019-12-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_auto_20191224_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='user',
        ),
    ]
