# Generated by Django 2.2.9 on 2019-12-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_auto_20191224_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
