# Generated by Django 2.2.9 on 2020-01-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.TextField(max_length=300),
        ),
    ]
