# Generated by Django 2.2.9 on 2020-01-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_auto_20200102_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
