# Generated by Django 2.2.9 on 2020-01-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_auto_20200102_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='creator',
        ),
    ]
