# Generated by Django 2.2.9 on 2020-01-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_auto_20200102_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
