# Generated by Django 2.2.9 on 2020-01-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_auto_20200102_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Profile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Position'),
        ),
        migrations.AlterField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Project'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
