# Generated by Django 2.2.9 on 2020-01-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_auto_20200103_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='positions',
        ),
        migrations.AddField(
            model_name='project',
            name='positions',
            field=models.ManyToManyField(blank=True, to='teams.Position'),
        ),
    ]
