# Generated by Django 2.2.9 on 2020-01-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_auto_20200104_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='positions',
            field=models.ManyToManyField(blank=True, to='teams.Position'),
        ),
    ]
