# Generated by Django 2.2.9 on 2020-01-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0030_auto_20200104_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='positions',
        ),
        migrations.AddField(
            model_name='position',
            name='project',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='teams.Project'),
        ),
    ]
