# Generated by Django 2.2.9 on 2020-01-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0032_auto_20200105_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='project',
        ),
    ]
