# Generated by Django 2.2.9 on 2020-01-05 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0034_position_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Project'),
        ),
    ]
